# Generated by Django 6.0.3 on 2026-04-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_wallet'),
        ('courses', '0005_course_tags_delete_coursetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('vendor', models.CharField(choices=[('click', 'click'), ('payme', 'payme'), ('uzum', 'uzum'), ('other', 'other')], max_length=20, verbose_name='vendor')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('canceled', 'canceled')], max_length=20, verbose_name='status')),
                ('currency', models.CharField(choices=[('uzs', 'uzs'), ('usd', 'usd'), ('eur', 'eur'), ('rub', 'rub')], max_length=20, verbose_name='currency')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='courses.course', verbose_name='course')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
