# Generated by Codex on 2026-05-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_stars_balance"),
        ("payments", "0002_order_unique_user_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="payments.order",
                verbose_name="order",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("top_up", "top up"), ("purchase", "purchase")],
                default="top_up",
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.wallet",
                verbose_name="wallet",
            ),
        ),
    ]
