# Generated by Django 6.0.3 on 2026-05-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_wallet_transaction_order_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='remote id'),
        ),
    ]
